name: ci

# workflow triggers
on:
  push:
    branches:
      - '**' # every branch
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  formatter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: code formatter
        run: |
          pip install wheel
          pip install black
          black --check src/
